version: '3'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - summarization-service
      - completion-service
      - auth-service

  summarization-service:
    build: ./summarization-service
    ports:
      - "8001:8001"

  completion-service:
    build: ./completion-service
    ports:
      - "8002:8002"

  auth-service:
    build: ./auth-service
    ports:
      - "8003:8003"
